name: PartyMusic
version: 1.0.0
main: com.bendude56.partymusic.PartyMusic
author: ben_dude56
depend: [Spout]
commands:
    music:
        usage:
        description: Sets the music playing
permissions:
    partymusic.*:
        description: Gives full access to PartyMusic commands
        children:
            partymusic.play: true
            partymusic.stop: true
            partymusic.list: true
            partymusic.set: true
    partymusic.play:
        description: Allows you to start playing music
        default: op
    partymusic.stop:
        description: Allows you to stop playing music
        default: op
    partymusic.list:
        description: Allows you to list all available music
        default: op
    partymusic.set:
        description: Allows you to set a music track to a URL
        default: op